### PR TITLE
Update MNIST.ipynb and Basic.ipynb to avoid Error Message

### PR DESCRIPTION
**Pull request by tarunjainsagar**
The update in the code removes the bug in the code which gives error on running code multiple times.

### CODE REVIEW

**Comment by tarunjainsagar** [comment]
@facebook-github-bot One check is failing above, how to find the error. Please guide. This is my first ever pull request.

**Comment by aaronmarkham** [comment]
@tarun1325 The Travis part timed-out, so it's not related to your changes. 
Regarding the changes, can you describe the steps you take to make the notebooks throw an error? Is it re-running specific blocks without re-running the whole notebook?

**Comment by tarunjainsagar** [comment]
@aaronmarkham 


Attached are the python files which I used to replicate MNIST.ipynb and Basic.ipynb 's example


[mnist_cnn.txt](https://github.com/caffe2/caffe2/files/978035/mnist_cnn.txt)
[16_RunNetOnce_vs_RunNet.txt](https://github.com/caffe2/caffe2/files/978036/16_RunNetOnce_vs_RunNet.txt)

**Explanation for MNIST.ipynb Changes:**
When we replicate the entire experiment in python code on any system, If you run this code first time, when you have not created any LEVELDB database, it will run smoothly.

Now, try running it again, In this case you already have LEVELDB data present in the directory. It will give such messages as show below and keep executing process:
```
terminate called after throwing an instance of 'caffe2::EnforceNotMet'

  what():  [enforce fail at leveldb.cc:70] status.ok(). Failed to open leveldb 

/home/tarun/downloads/new_caffe2/caffe2/python/examples/tarun_jain/02_MNIST_Model/tutorial_data/mnist/mnist-train-nchw-leveldb. Invalid argument: 

/home/tarun/downloads/new_caffe2/caffe2/python/examples/tarun_jain/02_MNIST_Model/tutorial_data/mnist/mnist-train-nchw-leveldb: exists (error_if_exists is true)

*** Aborted at 1493959840 (unix time) try "date -d @1493959840" if you are using GNU date ***
PC: @     0x7f2415d56c37 (unknown)

*** SIGABRT (@0x3ef000097aa) received by PID 38826 (TID 0x7f24178de840) from PID 38826; stack trace: ***
    @     0x7f2415d56cb0 (unknown)
    @     0x7f2415d56c37 (unknown)
    @     0x7f2415d5a028 (unknown)
    @     0x7f2416148535 (unknown)
    @     0x7f24161466d6 (unknown)
    @     0x7f2416146703 (unknown)
    @     0x7f2416146922 (unknown)
    @     0x7f2416670a46 _ZN6caffe210RegistererISsNS_2db2DBEJRKSsNS1_4ModeEEE14DefaultCreatorINS1_7LevelDBEEESt10unique_ptrIS2_St14default_deleteIS2_EES4_S5_
    @     0x7f2416628f8e std::_Function_handler<>::_M_invoke()
    @           0x4049e6 caffe2::convert_dataset()
    @           0x40371e main
    @     0x7f2415d41f45 (unknown)
    @           0x40374e (unknown)
    @                0x0 (unknown)
Aborted (core dumped)

```
**REASON FOR ERROR :** I have just added the condition to NOT call function to generateDB if they already exist from previous run. Refer to MNIST.ipynb changes.

**Explanation for BASICS.ipynb changes:**

If you don't make changes I commited, then you will get errors like this:
```

Traceback (most recent call last):
  File "16_RunNetOnce_vs_RunNet.py", line 40, in <module>
    workspace.RunNet(net.Proto().name)
  File "/home/tarun/downloads/new_caffe2/build/caffe2/python/workspace.py", line 173, in RunNet
    return C.run_net(StringifyNetName(name), num_iter)
RuntimeError: [enforce fail at pybind_state.cc:708] gWorkspace->GetNet(name). Can't find net my_first_net

```
**REASON FOR ERROR :** This is because you need to createNet before calling RunNet function.

In simple words, I want to say that example contains mistake in them. So I corrected it to be more robust.

**Comment by tarun1325** [comment]
Dear @aaronmarkham , when can i expect this pull request to be merged ?

**Comment by aaronmarkham** [comment]
For the MNIST tutorial it had already been refactored to deal with the db creation step and that particular crash but those earlier changes had not propagated yet. Hopefully that latency will go away not that we're in sync. For this reason I don't think we need to merge the PR for MNIST. Checkout the latest version of it and confirm.

I'm going to close this one, but can you create a new PR just for Basics? Then I'll import that one! Appreciate your contribution here. For the future it will always be better to have a PR for a single tutorial. Merging notebooks is already pretty messy, so one at a time is much easier to deal with.

Thanks!

**Comment by tarunjainsagar** [comment]
@aaronmarkham Where to check the Latest version of MNIST ?
I could see no change on github or caffe2.ai website. Can you please point out how did you handle it ?

**Comment by aaronmarkham** [comment]
https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb
In the second block, there's new code that checks for a lock file and deletes it:
```
    else:
        print "Database exists already. Delete the folder if you have issues/corrupted DB, then rerun this."
        if os.path.exists(os.path.join(name, "LOCK")):
            # print "Deleting the pre-existing lock file"
            os.remove(os.path.join(name, "LOCK"))
```

**Pull request closed without merging**
