### PR TITLE
Fix KeepOnShrink tests

### PR DESCRIPTION
**Pull request by lukeyeager**
Fix https://github.com/caffe2/caffe2/issues/417

### CODE REVIEW

**Comment by sunwael** [comment]
Can you re-trigger travis/appveyor to make sure failures are not related ?

**Comment by lukeyeager** [comment]
The tests don't actually run on TravisCI (see https://github.com/caffe2/caffe2/pull/550) - it just builds. Do they run on Appveyor?

**Comment by lukeyeager** [comment]
@sunwael Travis passed now, for what that's worth. Can you just take a look at the code? I'd like to get this merged so I can have a discussion with someone about https://github.com/caffe2/caffe2/pull/550.

**Pull request closed without merging**
