### PR TITLE
Edited Image_Pre-Processing_Pipeline.ipynb, reoder -> reorder

### PR DESCRIPTION
**Pull request by harderthan**
**Fixed typo**
I fixed typo on `caffe2/python/tutorials/Image_Pre-Processing_Pipeline.ipynb`.

> reoder -> reorder  

Please check below code.

### CODE REVIEW

**Comment by orionr** [comment]
@caffe2bot test this please

**Comment by orionr** [comment]
@harderthan - thanks for the contribution! Can you run
```
python caffe2/python/tutorials/tutorials_to_script_converter.py
```
and, if this adds any changes to the `py_gen` directory, add them to this PR? Thanks.

**Comment by harderthan** [comment]
I made a new commit for the changes. Could you check this?

**Comment by orionr** [comment]
Hi @harderthan. We did some significant work on the tutorials recently and it looks like this now has conflicts. Apologies. Looks like the typo still exists, though, so if you want to rebase and make the change again I'm happy to merge this in. Thanks for your contribution!

**Comment by harderthan** [comment]
I made the change again.
Please check this.

By the way, this is my first a pull request on github.
Thank you for your kindness.

**Comment by orionr** [comment]
Thank you for your contribution! PyTorch and Caffe2 are now officially merged with the PyTorch 1.0 preview release. Please submit on https://github.com/pytorch/pytorch if this is still an issue over there.

**Pull request closed without merging**
